// This file is auto-generated by @hey-api/openapi-ts

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type BoothAssignDevice = {
    device_id: string;
};

export type BoothConfigUpdate = {
    price_per_print?: (number | null);
    timer_default?: (number | null);
    max_print?: (number | null);
    filters?: (Array<(string)> | null);
    payment_timeout?: (number | null);
};

export type BoothCreate = {
    name: string;
    location?: (string | null);
    is_active?: boolean;
    config?: ({
    [key: string]: unknown;
} | null);
};

export type BoothPublic = {
    name: string;
    location?: (string | null);
    is_active?: boolean;
    id: string;
    device_id?: (string | null);
    current_session_id?: (string | null);
    config?: {
        [key: string]: unknown;
    };
    created_at?: (string | null);
    updated_at?: (string | null);
    last_active_at?: (string | null);
};

export type BoothsPublic = {
    data: Array<BoothPublic>;
    count: number;
};

export type BoothUpdate = {
    name?: (string | null);
    location?: (string | null);
    is_active?: (boolean | null);
};

export type DeviceSessionPublic = {
    device_id: string;
    device_name?: (string | null);
    id: string;
    booth_id?: (string | null);
    pin?: (string | null);
    is_active?: boolean;
    connected_at?: (string | null);
    last_heartbeat?: (string | null);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type ItemCreate = {
    title: string;
    description?: (string | null);
};

export type ItemPublic = {
    title: string;
    description?: (string | null);
    id: string;
    owner_id: string;
    created_at?: (string | null);
};

export type ItemsPublic = {
    data: Array<ItemPublic>;
    count: number;
};

export type ItemUpdate = {
    title?: (string | null);
    description?: (string | null);
};

export type KioskSessionPublic = {
    print_count?: number;
    filter_name?: string;
    timer?: number;
    id: string;
    booth_id: string;
    device_id: string;
    status: string;
    total_price?: (number | null);
    created_at?: (string | null);
    completed_at?: (string | null);
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type PaymentPublic = {
    amount: number;
    provider?: string;
    id: string;
    session_id: string;
    booth_id: string;
    status: string;
    reference_id?: (string | null);
    qr_string?: (string | null);
    transaction_id?: (string | null);
    paid_at?: (string | null);
    expires_at?: (string | null);
    created_at?: (string | null);
};

export type PaymentRequestBody = {
    amount: string;
    product_name?: string;
    qty?: string;
    booth_id: string;
    print_count?: number;
};

export type PhotoPublic = {
    file_url: string;
    order: number;
    id: string;
    session_id: string;
    created_at?: (string | null);
};

export type PhotosPublic = {
    data: Array<PhotoPublic>;
    count: number;
};

export type PhotoUploadBody = {
    session_id: string;
    photos: Array<PhotoUploadItem>;
};

export type PhotoUploadItem = {
    data_url: string;
    order: number;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type TransactionWithBooth = {
    amount: number;
    provider?: string;
    id: string;
    session_id: string;
    booth_id: string;
    status: string;
    reference_id?: (string | null);
    qr_string?: (string | null);
    transaction_id?: (string | null);
    paid_at?: (string | null);
    expires_at?: (string | null);
    created_at?: (string | null);
    booth_name?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
    created_at?: (string | null);
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

export type BoothsReadBoothsData = {
    limit?: number;
    skip?: number;
};

export type BoothsReadBoothsResponse = (BoothsPublic);

export type BoothsCreateBoothData = {
    requestBody: BoothCreate;
};

export type BoothsCreateBoothResponse = (BoothPublic);

export type BoothsReadBoothData = {
    id: string;
};

export type BoothsReadBoothResponse = (BoothPublic);

export type BoothsUpdateBoothData = {
    id: string;
    requestBody: BoothUpdate;
};

export type BoothsUpdateBoothResponse = (BoothPublic);

export type BoothsDeleteBoothData = {
    id: string;
};

export type BoothsDeleteBoothResponse = (Message);

export type BoothsUpdateBoothConfigData = {
    id: string;
    requestBody: BoothConfigUpdate;
};

export type BoothsUpdateBoothConfigResponse = (BoothPublic);

export type BoothsAssignDeviceData = {
    id: string;
    requestBody: BoothAssignDevice;
};

export type BoothsAssignDeviceResponse = (BoothPublic);

export type BoothsUnassignDeviceData = {
    id: string;
};

export type BoothsUnassignDeviceResponse = (BoothPublic);

export type DevicesRegisterDeviceData = {
    requestBody: {
        [key: string]: unknown;
    };
};

export type DevicesRegisterDeviceResponse = (DeviceSessionPublic);

export type DevicesCheckDeviceAssignmentData = {
    deviceId: string;
};

export type DevicesCheckDeviceAssignmentResponse = ({
    [key: string]: unknown;
});

export type DevicesDeviceHeartbeatData = {
    deviceId: string;
};

export type DevicesDeviceHeartbeatResponse = (DeviceSessionPublic);

export type DevicesAssignDeviceByPinData = {
    requestBody: {
        [key: string]: unknown;
    };
};

export type DevicesAssignDeviceByPinResponse = (BoothPublic);

export type ItemsReadItemsData = {
    limit?: number;
    skip?: number;
};

export type ItemsReadItemsResponse = (ItemsPublic);

export type ItemsCreateItemData = {
    requestBody: ItemCreate;
};

export type ItemsCreateItemResponse = (ItemPublic);

export type ItemsReadItemData = {
    id: string;
};

export type ItemsReadItemResponse = (ItemPublic);

export type ItemsUpdateItemData = {
    id: string;
    requestBody: ItemUpdate;
};

export type ItemsUpdateItemResponse = (ItemPublic);

export type ItemsDeleteItemData = {
    id: string;
};

export type ItemsDeleteItemResponse = (Message);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type PaymentsCreatePaymentData = {
    requestBody: PaymentRequestBody;
};

export type PaymentsCreatePaymentResponse = (unknown);

export type PaymentsCheckStatusData = {
    transactionId: string;
};

export type PaymentsCheckStatusResponse = (unknown);

export type PaymentsPaymentNotifyResponse = (unknown);

export type PaymentsPaymentNotifyTestData = {
    status: string;
    trxId: string;
};

export type PaymentsPaymentNotifyTestResponse = (unknown);

export type PaymentsCreateDemoPaymentData = {
    requestBody: PaymentRequestBody;
};

export type PaymentsCreateDemoPaymentResponse = (unknown);

export type PhotoboothAdminGetDashboardOverviewResponse = ({
    [key: string]: unknown;
});

export type PhotoboothAdminGetRecentTransactionsData = {
    limit?: number;
};

export type PhotoboothAdminGetRecentTransactionsResponse = (Array<TransactionWithBooth>);

export type PhotoboothAdminGetActiveSessionsResponse = (Array<KioskSessionPublic>);

export type PhotoboothAdminGetRecentSessionsData = {
    limit?: number;
};

export type PhotoboothAdminGetRecentSessionsResponse = (Array<KioskSessionPublic>);

export type PhotoboothAdminGetTransactionsData = {
    boothId?: (string | null);
    endDate?: (string | null);
    startDate?: (string | null);
    status?: (string | null);
};

export type PhotoboothAdminGetTransactionsResponse = (Array<PaymentPublic>);

export type PhotoboothAdminGetRevenueReportData = {
    /**
     * End date for the report
     */
    endDate: string;
    /**
     * Start date for the report
     */
    startDate: string;
};

export type PhotoboothAdminGetRevenueReportResponse = (Array<{
    [key: string]: unknown;
}>);

export type PhotosUploadPhotosData = {
    requestBody: PhotoUploadBody;
};

export type PhotosUploadPhotosResponse = (PhotosPublic);

export type PhotosGetPhotosBySessionData = {
    sessionId: string;
};

export type PhotosGetPhotosBySessionResponse = (PhotosPublic);

export type PhotosGetPhotoData = {
    photoId: string;
};

export type PhotosGetPhotoResponse = (PhotoPublic);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);

export type WebsocketGetOnlineDevicesResponse = (Array<{
    [key: string]: unknown;
}>);