"""add_pin_to_device_session

Revision ID: ed6adb75414b
Revises: 91316df2d857
Create Date: 2026-04-03 22:25:38.013498

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'ed6adb75414b'
down_revision = '91316df2d857'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device_sessions', sa.Column('pin', sqlmodel.sql.sqltypes.AutoString(length=6), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('device_sessions', 'pin')
    # ### end Alembic commands ###
